mybatis:
  type-aliases-package: com.sun.webblog.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mapper:
    mappers:
        - com.sun.webblog.util.MyMapper
    not-empty: false
    identity: MYSQL

spring:
    datasource:
        url: jdbc:mysql://192.168.186.10:3306/test?characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
     #   driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

    redis:
      cluster:
         nodes:  192.168.186.10:7000,192.168.186.10:7001,192.168.186.10:7002,192.168.186.10:7003,192.168.186.10:7004,192.168.186.10:7005,192.168.186.10:7006
         #nodes:  203.195.162.66:7000,203.195.162.66:7001,203.195.162.66:7002,203.195.162.66:7003,203.195.162.66:7004,203.195.162.66:7005
      jedis:
        pool:
          max-active: 100
          max-wait: 10s
          max-idle: 10
          min-idle: 5
      password: 123
      lettuce:
        shutdown-timeout: 10s
      timeout:  6000ms








